- name: Configuring SW-CORE-1
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: 123
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: 123

  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - "hostname SW-CORE-1"

    - name: Configure spanning-tree
      ios_config:
        lines:
          - "spanning-tree vlan 10 root primary"
          - "spanning-tree vlan 20 root primary"

    - name: Create VLANs
      ios_config:
        lines:
          - "vlan {{ item }}"
      loop:
        - 10
        - 20
        - 100

    - name: Configure tracking
      ios_config:
        lines:
          - "track 10 int gi0/1 line-protocol"
          - "track 20 int gi0/1 line-protocol"

    - name: Configure VLAN 10
      ios_config:
        lines:
          - "no shut"
          - "ip address 192.168.10.2 255.255.255.0"
          - "standby 10 ip 192.168.10.1"
          - "standby 10 priority 110"
          - "standby 10 preempt"
          - "standby 10 track 10 decrement 20"
          - "standby 10 authentication 123"
        parents: "int vlan 10"

    - name: Configure VLAN 20
      ios_config:
        lines:
          - "no shut"
          - "ip address 172.16.20.2 255.255.255.0"
          - "standby 20 ip 172.16.20.1"
          - "standby 20 priority 110"
          - "standby 20 preempt"
          - "standby 20 track 20 decrement 20"
          - "standby 20 authentication 123"
        parents: "int vlan 20"

    - name: Configure VLAN 100
      ios_config:
        lines:
          - "no shut"
          - "ip address 172.16.110.242 255.255.255.0"
        parents: "int vlan 100"

    - name: Enable IP routing
      ios_config:
        lines:
          - "ip routing"

    - name: Configure default gateway
      ios_config:
        lines:
          - "ip default-gateway 172.16.110.241"

    - name: Configure int gi0/0
      ios_config:
        lines:
          - "no shut"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
        parents: "int gi0/0"

    - name: Configure int gi0/1
      ios_config:
        lines:
          - "no shut"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
        parents: "int gi0/1"