- name: Configuring SW-CORE-1
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: 123
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: 123

  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - "hostname SW-CORE-1"

    - name: Configure spanning-tree
      ios_config:
        lines:
          - "spanning-tree vlan 10 root primary"
          - "spanning-tree vlan 20 root primary"

    - name: Create VLANs
      ios_config:
        lines:
          - "vlan {{ item }}"
      loop:
        - 10
        - 20
        - 100

    - name: Configure tracking
      ios_config:
        lines:
          - "track 10 int gi0/1 line-protocol"
          - "track 20 int gi0/1 line-protocol"

    - name: Configure VLAN 10
      ios_config:
        lines:
          - "no shut"
          - "ip address 192.168.10.2 255.255.255.0"
          - "standby 10 ip 192.168.10.1"
          - "standby 10 priority 110"
          - "standby 10 preempt"
          - "standby 10 track 10 decrement 20"
          - "standby 10 authentication 123"
        parents: "int vlan 10"

    - name: Configure VLAN 20
      ios_config:
        lines:
          - "no shut"
          - "ip address 172.16.20.2 255.255.255.0"
          - "standby 20 ip 172.16.20.1"
          - "standby 20 priority 110"
          - "standby 20 preempt"
          - "standby 20 track 20 decrement 20"
          - "standby 20 authentication 123"
        parents: "int vlan 20"

    - name: Configure VLAN 100
      ios_config:
        lines:
          - "no shut"
          - "ip address 172.16.110.242 255.255.255.0"
        parents: "int vlan 100"

    - name: Enable IP routing
      ios_config:
        lines:
          - "ip routing"

    - name: Configure default gateway
      ios_config:
        lines:
          - "ip default-gateway 172.16.110.241"

    - name: Configure int gi0/0
      ios_config:
        lines:
          - "no shut"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
        parents: "int gi0/0"

    - name: Configure int gi0/1
      ios_config:
        lines:
          - "no shut"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
        parents: "int gi0/1"

- name: Configuring SW-CORE-2
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: 123
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: 123

  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - "hostname SW-CORE-2"

    - name: Configure spanning-tree
      ios_config:
        lines:
          - "spanning-tree vlan 10 root secondary"
          - "spanning-tree vlan 20 root secondary"

    - name: Create VLANs
      ios_config:
        lines:
          - "vlan {{ item }}"
      loop:
        - 10
        - 20
        - 100

    - name: Configure tracking
      ios_config:
        lines:
          - "track 10 int gi0/1 line-protocol"
          - "track 20 int gi0/1 line-protocol"

    - name: Configure VLAN 10
      ios_config:
        lines:
          - "no shut"
          - "ip address 192.168.10.3 255.255.255.0"
          - "standby 10 ip 192.168.10.1"
          - "standby 10 priority 100"
          - "standby 10 preempt"
          - "standby 10 track 10 decrement 20"
          - "standby 10 authentication 123"
        parents: "int vlan 10"

    - name: Configure VLAN 20
      ios_config:
        lines:
          - "no shut"
          - "ip address 172.16.20.3 255.255.255.0"
          - "standby 20 ip 172.16.20.1"
          - "standby 20 priority 100"
          - "standby 20 preempt"
          - "standby 20 track 20 decrement 20"
          - "standby 20 authentication 123"
        parents: "int vlan 20"

    - name: Configure VLAN 100
      ios_config:
        lines:
          - "no shut"
          - "ip address 172.16.110.243 255.255.255.0"
        parents: "int vlan 100"

    - name: Enable IP routing
      ios_config:
        lines:
          - "ip routing"

    - name: Configure default gateway
      ios_config:
        lines:
          - "ip default-gateway 172.16.110.241"

    - name: Configure int gi0/0
      ios_config:
        lines:
          - "no shut"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
        parents: "int gi0/0"

    - name: Configure int gi0/1
      ios_config:
        lines:
          - "no shut"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
        parents: "int gi0/1"

- name: Configuring SW-ACC-1
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: 123
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: 123

  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - "hostname SW-ACC-1"

    - name: Create VLANs
      ios_config:
        lines:
          - "vlan {{ item }}"
      loop:
        - 10
        - 20

    - name: Configure int gi0/0
      ios_config:
        lines:
          - "no shut"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
        parents: "int gi0/0"

    - name: Configure int gi0/1
      ios_config:
        lines:
          - "no shut"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
        parents: "int gi0/1"

    - name: Configure int gi0/2
      ios_config:
        lines:
          - "no shut"
          - "switchport mode access"
          - "switchport access vlan 10"
          - "spanning-tree portfast"
          - "spanning-tree bpduguard enable"
        parents: "int gi0/2"

- name: Configuring SW-ACC-2
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: 123
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: 123

  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - "hostname SW-ACC-2"

    - name: Create VLANs
      ios_config:
        lines:
          - "vlan {{ item }}"
      loop:
        - 10
        - 20

    - name: Configure int gi0/0
      ios_config:
        lines:
          - "no shut"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
        parents: "int gi0/0"

    - name: Configure int gi0/1
      ios_config:
        lines:
          - "no shut"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
        parents: "int gi0/1"

    - name: Configure int gi0/2
      ios_config:
        lines:
          - "no shut"
          - "switchport mode access"
          - "switchport access vlan 20"
          - "spanning-tree portfast"
          - "spanning-tree bpduguard enable"
        parents: "int gi0/2"

- name: Configuring RTR-1
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: 123
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: 123

  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - "hostname RTR-EDGE"

    - name: Configure gi0/0
      ios_config:
        lines:
          - "no shut"
          - "ip nat inside"
        parents: "int gi0/0"

    - name: Configure gi0/1
      ios_config:
        lines:
          - "no shut"
          - "ip nat inside"
        parents: "int gi0/1"

    - name: Configure gi0/2
      ios_config:
        lines:
          - "no shut"
          - "ip address 85.133.165.2 255.255.255.252"
          - "ip nat outside"
        parents: "int gi0/2"

    - name: Configure gi0/3
      ios_config:
        lines:
          - "no shut"
          - "ip address 100.203.0.2 255.255.255.252"
          - "ip nat outside"
        parents: "int gi0/3"

    - name: Configure NAT access list
      ios_config:
        lines:
          - "10 permit 192.168.10.0 0.0.0.255"
          - "20 permit 172.16.20.0 0.0.0.255"
        parents: "ip access-list standard 10"

    - name: Configure NAT overload on gi0/2
      ios_config:
        lines:
          - "ip nat source list 10 int gi0/2 overload"

    - name: Configure default route
      ios_config:
        lines:
          - "ip route 0.0.0.0 0.0.0.0 85.133.165.1"

    - name: Configure IP SLA
      ios_config:
        lines:
          - "icmp-echo 85.133.165.1"
          - "frequency 10"
          - "timeout 1000"
        parents: "ip sla 1"

    - name: Schedule IP SLA
      ios_config:
        lines:
          - "ip sla schedule 1 start-time now life forever"

    - name: Configure tracking for IP SLA
      ios_config:
        lines:
          - "track 1 ip sla 1 state"
          - "track 1 ip sla 1 reachability"

    - name: Configure EEM Applet - Failover default route down
      ios_config:
        lines:
          - "event track 1 state down"
          - "action 1.0 cli command \"enable\""
          - "action 2.0 cli command \"conf t\""
          - "action 3.0 cli command \"no ip nat source list 10 int gi0/2 overload\""
          - "action 4.0 cli command \"no ip route 0.0.0.0 0.0.0.0 85.133.165.1\""
          - "action 5.0 cli command \"ip nat source list 10 int gi0/3 overload\""
          - "action 6.0 cli command \"ip route 0.0.0.0 0.0.0.0 100.203.0.1\""
        parents: "event manager applet Failover_default_route_down"

    - name: Configure EEM Applet - Failover default route up
      ios_config:
        lines:
          - "event track 1 state up"
          - "action 1.0 cli command \"enable\""
          - "action 2.0 cli command \"conf t\""
          - "action 3.0 cli command \"no ip nat source list 10 int gi0/3 overload\""
          - "action 4.0 cli command \"no ip route 0.0.0.0 0.0.0.0 100.203.0.1\""
          - "action 5.0 cli command \"ip nat source list 10 int gi0/2 overload\""
          - "action 6.0 cli command \"ip route 0.0.0.0 0.0.0.0 85.133.165.1\""
        parents: "event manager applet Failover_default_route_up"

- name: Configuring RTR-ISP-1
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: 123
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: 123

  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - "hostname RTR-ISP-1"

    - name: Configure gi0/0
      ios_config:
        lines:
          - "no shut"
          - "ip address 85.133.165.1 255.255.255.252"
        parents: "int gi0/0"

    - name: Configure loopback interface
      ios_config:
        lines:
          - "no shut"
          - "ip address 8.8.8.8 255.255.255.0"
        parents: "int loopback 1"
        
- name: Configuring RTR-ISP-2
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: 123
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: 123

  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - "hostname RTR-ISP-2"

    - name: Configure gi0/0
      ios_config:
        lines:
          - "no shut"
          - "ip address 100.203.0.1 255.255.255.0"
        parents: "int gi0/0"

    - name: Configure loopback interface
      ios_config:
        lines:
          - "no shut"
          - "ip address 8.8.8.8 255.255.255.0"
        parents: "int loopback 1"
